### ISSUE TITLE
영문 튜터리얼에서 CLI 생성기 부분이 삭제된것 같네요.

### ISSUE THREAD

**Issue by starman1108** [hoksi/ci4userguidekr#5]
영문주소 확인부탁드립니다.
https://codeigniter4.github.io/userguide/cli/index.html

**Comment by hoksi** [comment]
4.0.5에 반영될 모양입니다.
https://github.com/codeigniter4/CodeIgniter4/blob/develop/user_guide_src/source/cli/cli_generators.rst

메뉴얼이 개발 버전에 맞추어서 번역중이라...

**Comment by starman1108** [comment]
네 저도 최신 버전 다운받아서 가이드보면서 해보다가 CLI생성기부분이 작동이 안되서 보니 영문링크에서는 해당 부분이 삭제되었더라구요.^^
